name: Deploy

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p build
      - run: cp {app.js,ecosystem.config.js,package.json,package-lock.json} build
      - run: npm install --prefix build
      - uses: delasy/blue-green-deployment@v1
        with:
          name: ${{ secrets.NAME }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          source: ./build
